(function(global){
'use strict';
const MAX_MONTHS=1200,MODES=['sip','lumpsum','stepup'];
function finite(n,label='Result'){if(!Number.isFinite(n))throw new Error(label+' is outside the supported range. Reduce the amount, rate, step-up or term.');return n}
function requireNumber(v,label,min=-Infinity,max=Infinity){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`Enter a valid ${label}.`);return n}
function validMode(mode){if(!MODES.includes(mode))throw new Error('Choose SIP, lump sum or step-up SIP.');return mode}
function monthlyRate(annual){if(annual<=-100||annual>1000)throw new Error('Expected annual return must be above -100% and at most 1,000%.');return Math.pow(1+annual/100,1/12)-1}
function contributionForMonth(base,stepPct,stepEveryMonths,m){return finite(base*Math.pow(1+stepPct/100,Math.floor(m/stepEveryMonths)),'Monthly contribution')}
function project(input){const mode=validMode(input.mode||'sip'),months=requireNumber(input.months,'investment term',1,MAX_MONTHS);if(!Number.isInteger(months))throw new Error('Investment term must be a whole number of months.');const annual=requireNumber(input.annualReturn,'expected annual return',-99.999,1000),inflation=requireNumber(input.inflation||0,'inflation rate',-99.999,1000),r=monthlyRate(annual);let lump=0,base=0,step=0,stepEvery=12;if(mode==='lumpsum')lump=requireNumber(input.lumpSum,'lump-sum investment',0,1e15);else{base=requireNumber(input.monthly,'monthly investment',0,1e15);if(base===0)throw new Error('Monthly investment must be greater than zero.');if(mode==='stepup'){step=requireNumber(input.stepPct,'step-up rate',-99,1000);stepEvery=requireNumber(input.stepEveryMonths==null?12:input.stepEveryMonths,'step-up interval',1,120);if(!Number.isInteger(stepEvery))throw new Error('Step-up interval must be a whole number of months.');}}if(mode==='lumpsum'&&lump===0)throw new Error('Lump-sum investment must be greater than zero.');let balance=lump,invested=lump;const monthly=[],yearly=[];for(let m=1;m<=months;m++){const contribution=mode==='lumpsum'?0:contributionForMonth(base,step,stepEvery,m-1);balance=finite(balance*(1+r)+contribution,'Projected value');invested=finite(invested+contribution,'Invested amount');const row={month:m,contribution,balance,invested,gains:balance-invested};monthly.push(row);if(m%12===0||m===months)yearly.push({...row,year:Math.ceil(m/12)});}const years=months/12,realValue=finite(balance/Math.pow(1+inflation/100,years),'Inflation-adjusted value'),gains=balance-invested,cagr=mode==='lumpsum'&&lump>0&&years>0?(Math.pow(balance/lump,1/years)-1)*100:null;return{mode,months,annualReturn:annual,inflation,invested:finite(invested),value:finite(balance),gains:finite(gains),realValue,cagr:cagr===null?null:finite(cagr),monthly,yearly};}
function solveGoal(input){const target=requireNumber(input.target,'goal amount',.01,1e15),months=requireNumber(input.months,'goal term',1,MAX_MONTHS);if(!Number.isInteger(months))throw new Error('Goal term must be a whole number of months.');const annual=requireNumber(input.annualReturn,'expected annual return',-99.999,1000),inflation=requireNumber(input.inflation||0,'inflation rate',-99.999,1000),mode=validMode(input.mode||'sip'),targetFuture=finite(input.targetIsTodayValue?target*Math.pow(1+inflation/100,months/12):target,'Future goal value'),common={mode,months,annualReturn:annual,inflation,stepPct:input.stepPct==null?0:input.stepPct,stepEveryMonths:input.stepEveryMonths==null?12:input.stepEveryMonths};let lo=0,hi=1;const valueFor=x=>{try{return project({...common,...(mode==='lumpsum'?{lumpSum:x}:{monthly:x})}).value}catch(e){if(/outside the supported range/.test(e.message))return Infinity;throw e}};while(hi<1e15&&valueFor(hi)<targetFuture)hi=Math.min(hi*2,1e15);if(valueFor(hi)<targetFuture)throw new Error('Goal is outside the supported calculation range.');for(let i=0;i<100;i++){const mid=(lo+hi)/2;if(valueFor(mid)>=targetFuture)hi=mid;else lo=mid;}return{required:hi,targetFuture,targetToday:target,targetIsTodayValue:!!input.targetIsTodayValue};}
const api={project,solveGoal,monthlyRate};if(typeof module!=='undefined'&&module.exports)module.exports=api;global.InvestmentEngine=api;
})(typeof window!=='undefined'?window:globalThis);
