const $=s=>document.querySelector(s);
const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:0,maximumFractionDigits:2});
let current=null;
const EPS=1e-8, cents=n=>Math.round((n+Number.EPSILON)*100)/100;
function assertFinite(n,msg){if(!Number.isFinite(n))throw Error(msg);return n}
function inputs(){const P=assertFinite(Number($('#principal').value),'Enter a valid loan amount.'),rate=assertFinite(Number($('#rate').value),'Enter a valid annual interest rate.'),ten=assertFinite(Number($('#tenure').value),'Enter a valid tenure.'),unit=$('#tenure-unit').value,fee=assertFinite(Number($('#fee').value||0),'Enter a valid processing fee.');if(P<=0||P>1e10)throw Error('Loan amount must be greater than ₹0 and no more than ₹10,00,00,00,000.');if(rate<0||rate>100)throw Error('Annual interest rate must be between 0% and 100%.');if(ten<=0)throw Error('Tenure must be greater than zero.');const rawMonths=unit==='years'?ten*12:ten;if(Math.abs(rawMonths-Math.round(rawMonths))>EPS)throw Error('Tenure must resolve to a whole number of months.');const months=Math.round(rawMonths);if(months<1||months>1200)throw Error('Tenure must be between 1 and 1,200 months (100 years).');if(fee<0||fee>P)throw Error('Processing fee must be between ₹0 and the loan amount.');return{P:cents(P),rate,months,fee:cents(fee),method:$('#interest-method').value,type:$('#loan-type').value}}
function finalize(P,s){const principal=s.reduce((a,x)=>a+x.principal,0),total=s.reduce((a,x)=>a+x.payment,0),interest=s.reduce((a,x)=>a+x.interest,0);if(Math.abs(principal-P)>0.05)throw Error('Calculation integrity check failed. Please adjust the inputs and try again.');return{payment:s[0]?.payment||0,total,interest,schedule:s,principal:P}}
function reducing(P,annual,n){if(annual===0)return equalPrincipal(P,n,0);const r=annual/1200;const pow=Math.pow(1+r,n);if(!Number.isFinite(pow))throw Error('This rate and tenure combination is too large to calculate reliably.');const regular=P*r*pow/(pow-1);let bal=P,s=[];for(let i=1;i<=n;i++){const interest=bal*r;let principal=regular-interest,payment=regular;if(i===n||principal>bal){principal=bal;payment=principal+interest}bal=Math.max(0,bal-principal);s.push({period:i,payment,principal,interest,balance:bal})}return finalize(P,s)}
function equalPrincipal(P,n,totalInterest){let bal=P,s=[];const basePrincipal=P/n,baseInterest=totalInterest/n;for(let i=1;i<=n;i++){const principal=i===n?bal:basePrincipal,interest=baseInterest,payment=principal+interest;bal=Math.max(0,bal-principal);s.push({period:i,payment,principal,interest,balance:bal})}return finalize(P,s)}
function flat(P,annual,n){return equalPrincipal(P,n,P*(annual/100)*(n/12))}
function simple(P,annual,n){return equalPrincipal(P,n,P*(annual/100)*(n/12))}
function interestOnly(P,annual,n){const monthly=P*(annual/1200),s=[];for(let i=1;i<=n;i++){const principal=i===n?P:0,interest=monthly,payment=principal+interest;s.push({period:i,payment,principal,interest,balance:i===n?0:P})}return finalize(P,s)}
function calculate(v){switch(v.method){case'reducing':return reducing(v.P,v.rate,v.months);case'flat':return flat(v.P,v.rate,v.months);case'simple':return simple(v.P,v.rate,v.months);case'interest-only':return interestOnly(v.P,v.rate,v.months);default:throw Error('Choose a valid interest method.')}}
function annualize(rows){const out=[];for(let i=0;i<rows.length;i+=12){const g=rows.slice(i,i+12),last=g[g.length-1];out.push({period:'Year '+(i/12+1),payment:g.reduce((a,x)=>a+x.payment,0),principal:g.reduce((a,x)=>a+x.principal,0),interest:g.reduce((a,x)=>a+x.interest,0),balance:last.balance})}return out}
function td(text){const x=document.createElement('td');x.textContent=text;return x}
function renderSchedule(view='monthly'){if(!current)return;const rows=view==='yearly'?annualize(current.calc.schedule):current.calc.schedule,frag=document.createDocumentFragment();for(const x of rows){const tr=document.createElement('tr');tr.append(td(x.period),td(money.format(cents(x.payment))),td(money.format(cents(x.principal))),td(money.format(cents(x.interest))),td(money.format(cents(x.balance))));frag.append(tr)}$('#schedule-body').replaceChildren(frag)}
function render(v,x){current={v,calc:x};$('#results').hidden=false;$('#payment-label').textContent=v.method==='interest-only'?'Initial monthly interest payment':'Estimated monthly payment';$('#payment').textContent=money.format(cents(x.payment));$('#r-principal').textContent=money.format(v.P);$('#r-interest').textContent=money.format(cents(x.interest));$('#r-total').textContent=money.format(cents(x.total+v.fee));$('#r-fees').textContent=money.format(v.fee);const denom=v.P+x.interest,p=denom?v.P/denom*100:100;$('#principal-bar').style.width=p+'%';$('#interest-bar').style.width=(100-p)+'%';$('#split-text').textContent=`Principal ${p.toFixed(1)}% · Interest ${(100-p).toFixed(1)}%`;$('#method-note').textContent=`${v.type} · ${$('#interest-method').selectedOptions[0].textContent} · ${v.months} months`;$('#prepay-result').replaceChildren();renderSchedule();$('#results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
$('#loan-form').addEventListener('submit',e=>{e.preventDefault();const err=$('#form-error');try{err.hidden=true;const v=inputs();render(v,calculate(v))}catch(ex){err.textContent=ex instanceof Error?ex.message:'Unable to calculate these values.';err.hidden=false}})
document.querySelectorAll('.view-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view-btn').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))});renderSchedule(b.dataset.view)}));
function addPrepayResult(saved,revised,monthsSaved,extra){const box=document.createElement('div');box.className='prepay-stats';const values=[['Interest saved',money.format(cents(saved))],['New monthly payment',money.format(cents(revised.payment))],['New tenure',revised.schedule.length+' months'],['Months saved',String(monthsSaved)],['Upfront prepayment',money.format(cents(extra))]];for(const [k,v] of values){const row=document.createElement('span');const strong=document.createElement('strong');strong.textContent=k+': ';row.append(strong,document.createTextNode(v));box.append(row)}$('#prepay-result').replaceChildren(box)}
function prepayImpact(){if(!current)return;const extra=Number($('#prepay').value);if(!Number.isFinite(extra)||extra<=0){$('#prepay-result').textContent='Enter an extra payment greater than zero.';return}const {v,calc}=current;if(v.method!=='reducing'){$('#prepay-result').textContent='Prepayment modelling is available for reducing-balance loans. Other methods can depend heavily on lender-specific pre-closure rules.';return}if(extra>=v.P){$('#prepay-result').textContent='Extra payment must be less than the original principal for this comparison.';return}const newP=v.P-extra,mode=$('#prepay-mode').value;let revised;if(mode==='emi')revised=reducing(newP,v.rate,v.months);else{const oldPay=calc.payment,r=v.rate/1200;let n;if(r===0)n=Math.ceil(newP/oldPay);else{const q=1-r*newP/oldPay;if(q<=0)n=1;else n=Math.ceil(-Math.log(q)/Math.log(1+r))}n=Math.min(v.months,Math.max(1,n));revised=reducing(newP,v.rate,n)}const saved=Math.max(0,calc.interest-revised.interest);addPrepayResult(saved,revised,Math.max(0,v.months-revised.schedule.length),extra)}
$('#prepay-btn').addEventListener('click',prepayImpact);
const helps={reducing:'Reducing balance: each month’s interest is calculated on the outstanding principal. This is the standard fixed-EMI model used here.',flat:'Flat rate: total interest is calculated on the original principal for the full tenure, then spread across payments.',simple:'Simple interest: principal × annual rate × time. For this planning view, principal and total interest are spread across the selected term.',"interest-only":'Interest-only: monthly payments cover interest; this estimate assumes the entire principal is repaid with the final payment.'};
function updateHelp(){$('#method-help').textContent=helps[$('#interest-method').value]}$('#interest-method').addEventListener('change',updateHelp);updateHelp();
export{reducing,flat,simple,interestOnly,calculate};