(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.LoanEngine=api;})(typeof window!=='undefined'?window:null,function(){'use strict';
const EPS=1e-8;
function finite(n,m){if(!Number.isFinite(n))throw Error(m||'Invalid number.');return n}
function validate(P,annual,n){finite(P);finite(annual);finite(n);if(P<=0)throw Error('Principal must be greater than zero.');if(annual<0||annual>100)throw Error('Annual rate must be between 0% and 100%.');if(n<1||n>1200||Math.floor(n)!==n)throw Error('Tenure must be 1–1,200 whole months.')}
function row(period,opening,payment,principal,interest,extra,closing){return{period,opening,payment,principal,interest,extra:extra||0,balance:Math.max(0,closing)}}
function finish(P,s,meta){const principal=s.reduce((a,x)=>a+x.principal+x.extra,0),interest=s.reduce((a,x)=>a+x.interest,0),payments=s.reduce((a,x)=>a+x.payment+x.extra,0);if(Math.abs(principal-P)>0.08)throw Error('Calculation integrity check failed.');return Object.assign({payment:s.length?s[0].payment:0,total:payments,interest,schedule:s,principal:P},meta||{})}
function reducing(P,annual,n){validate(P,annual,n);if(annual===0){let b=P,s=[];const pay=P/n;for(let i=1;i<=n;i++){const o=b,pr=i===n?b:pay;b=Math.max(0,b-pr);s.push(row(i,o,pr,pr,0,0,b))}return finish(P,s)}
 const r=annual/1200,pow=Math.pow(1+r,n);if(!Number.isFinite(pow))throw Error('Rate and tenure combination is too large.');const emi=P*r*pow/(pow-1);let b=P,s=[];for(let i=1;i<=n;i++){const o=b,int=o*r;let pr=emi-int,pay=emi;if(i===n||pr>b){pr=b;pay=pr+int}b=Math.max(0,b-pr);s.push(row(i,o,pay,pr,int,0,b))}return finish(P,s)}
function fixed(P,annual,n,kind){validate(P,annual,n);const totalInterest=P*(annual/100)*(n/12),pr=P/n,int=totalInterest/n,pay=pr+int;let b=P,s=[];for(let i=1;i<=n;i++){const o=b,p=i===n?b:pr,pm=i===n?p+int:pay;b=Math.max(0,b-p);s.push(row(i,o,pm,p,int,0,b))}return finish(P,s,{kind})}
function interestOnly(P,annual,n){validate(P,annual,n);const int=P*(annual/1200),s=[];for(let i=1;i<=n;i++){const pr=i===n?P:0;s.push(row(i,P,pr+int,pr,int,0,i===n?0:P))}return finish(P,s,{structure:'interest-only-balloon'})}
function fixedPaymentPayoff(P,annual,payment,maxMonths){validate(P,annual,Math.min(1200,maxMonths||1200));finite(payment);if(payment<=0)throw Error('Payment must be greater than zero.');const r=annual/1200;if(r>0&&payment<=P*r+EPS)throw Error('Payment is too low to amortize this balance.');let b=P,s=[],cap=Math.min(1200,maxMonths||1200);for(let i=1;i<=cap&&b>EPS;i++){const o=b,int=o*r,need=o+int,pay=Math.min(payment,need),pr=pay-int;if(pr<=0&&b>EPS)throw Error('Payment does not reduce principal.');b=Math.max(0,b-pr);s.push(row(i,o,pay,pr,int,0,b))}if(b>0.05)throw Error('Loan does not repay within the supported term.');return finish(P,s,{regularPayment:payment})}
function stepped(P,annual,n,stepPct,direction,stepEvery){validate(P,annual,n);finite(stepPct);stepEvery=stepEvery||12;if(stepPct<0||stepPct>50)throw Error('Step percentage must be between 0% and 50%.');if(stepEvery<1||Math.floor(stepEvery)!==stepEvery)throw Error('Step frequency must be whole months.');const sign=direction==='down'?-1:1,factor=1+sign*stepPct/100;if(factor<=0)throw Error('Invalid step pattern.');const r=annual/1200;let pvFactor=0;for(let t=1;t<=n;t++){const k=Math.floor((t-1)/stepEvery),mult=Math.pow(factor,k);pvFactor+=mult/Math.pow(1+r,t)}if(pvFactor<=0||!Number.isFinite(pvFactor))throw Error('Unable to solve stepped repayment.');const start=P/pvFactor;let b=P,s=[];for(let t=1;t<=n;t++){const o=b,int=o*r,k=Math.floor((t-1)/stepEvery),scheduled=start*Math.pow(factor,k);let pay=scheduled,pr=pay-int;if(t===n||pr>b){pr=b;pay=pr+int}if(pr<0)throw Error('This stepped-payment pattern falls below accrued monthly interest and would create negative amortization. Adjust the step percentage, rate or tenure.');b=Math.max(0,b-pr);s.push(row(t,o,pay,pr,int,0,b))}return finish(P,s,{structure:direction==='down'?'step-down':'step-up',startPayment:start,stepPct,stepEvery})}
function balloon(P,annual,n,B){validate(P,annual,n);finite(B);if(B<0||B>=P)throw Error('Balloon must be at least zero and less than principal.');const r=annual/1200;let pay;if(r===0)pay=(P-B)/n;else{const pow=Math.pow(1+r,n);pay=(P-B/pow)*r*pow/(pow-1)}let b=P,s=[];for(let i=1;i<=n;i++){const o=b,int=o*r;let pr=pay-int,pm=pay;if(i===n){pr=b;pm=pr+int}else if(pr>b-B){pr=b-B;pm=pr+int}b=Math.max(0,b-pr);s.push(row(i,o,pm,pr,int,0,b))}return finish(P,s,{structure:'balloon',balloon:B,regularPayment:pay})}
function moratorium(P,annual,months,capitalize){finite(months);if(months<0||months>120||Math.floor(months)!==months)throw Error('Moratorium must be 0–120 whole months.');const r=annual/1200;let b=P,s=[],interestPaid=0;for(let i=1;i<=months;i++){const o=b,int=o*r;if(capitalize){b=o+int;s.push({period:i,opening:o,payment:0,principal:0,interest:int,extra:0,balance:b,moratorium:true,capitalized:true})}else{interestPaid+=int;s.push({period:i,opening:o,payment:int,principal:0,interest:int,extra:0,balance:b,moratorium:true,capitalized:false})}}return{balance:b,schedule:s,interestPaid,capitalizedInterest:b-P}}
function withMoratorium(P,annual,n,m,capitalize){validate(P,annual,n);if(m>=n)throw Error('Moratorium must be shorter than total tenure.');const pre=moratorium(P,annual,m,capitalize),main=reducing(pre.balance,annual,n-m),shifted=main.schedule.map(x=>Object.assign({},x,{period:x.period+m})),all=pre.schedule.concat(shifted);const totalInterest=all.reduce((a,x)=>a+x.interest,0),total=all.reduce((a,x)=>a+x.payment+x.extra,0);return{payment:main.payment,total,interest:totalInterest,schedule:all,principal:P,balanceAtRepaymentStart:pre.balance,capitalizedInterest:pre.capitalizedInterest,structure:'moratorium-standard'}}
function calculate(v){const stepPct=v.stepPct==null?5:v.stepPct,stepEvery=v.stepEvery==null?12:v.stepEvery,balloonAmount=v.balloon==null?0:v.balloon,moratoriumMonths=v.moratoriumMonths==null?0:v.moratoriumMonths;if(v.structure==='step-up')return stepped(v.P,v.rate,v.months,stepPct,'up',stepEvery);if(v.structure==='step-down')return stepped(v.P,v.rate,v.months,stepPct,'down',stepEvery);if(v.structure==='balloon')return balloon(v.P,v.rate,v.months,balloonAmount);if(v.structure==='moratorium')return withMoratorium(v.P,v.rate,v.months,moratoriumMonths,!!v.capitalizeMoratorium);if(v.method==='flat')return fixed(v.P,v.rate,v.months,'flat');if(v.method==='simple')return fixed(v.P,v.rate,v.months,'simple');if(v.method==='interest-only')return interestOnly(v.P,v.rate,v.months);return reducing(v.P,v.rate,v.months)}
return{calculate,reducing,fixedPaymentPayoff,stepped,balloon,moratorium,withMoratorium,interestOnly,flat:(P,a,n)=>fixed(P,a,n,'flat'),simple:(P,a,n)=>fixed(P,a,n,'simple')};});