const $=s=>document.querySelector(s);
const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
let current=null;
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
function inputs(){const P=Number($('#principal').value),rate=Number($('#rate').value),ten=Number($('#tenure').value),unit=$('#tenure-unit').value,fee=Number($('#fee').value||0);const months=unit==='years'?Math.round(ten*12):Math.round(ten);if(!Number.isFinite(P)||P<=0)throw Error('Enter a loan amount greater than zero.');if(!Number.isFinite(rate)||rate<0||rate>100)throw Error('Enter an annual interest rate between 0% and 100%.');if(!Number.isFinite(months)||months<1||months>1200)throw Error('Tenure must be between 1 and 1,200 months.');if(!Number.isFinite(fee)||fee<0||fee>P)throw Error('Processing fee must be between ₹0 and the loan amount.');return{P,rate,months,fee,method:$('#interest-method').value,type:$('#loan-type').value}}
function reducing(P,annual,n){if(annual===0){const pay=P/n;return scheduleFixed(P,n,pay,0)}const r=annual/1200;const pay=P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);let bal=P,s=[];for(let i=1;i<=n;i++){let interest=bal*r,principal=pay-interest,payment=pay;if(i===n){principal=bal;payment=principal+interest}bal=Math.max(0,bal-principal);s.push({period:i,payment,principal,interest,balance:bal})}return finalize(P,s)}
function scheduleFixed(P,n,payment,totalInterest){let bal=P,s=[],principal=P/n,interest=totalInterest/n;for(let i=1;i<=n;i++){bal=Math.max(0,bal-principal);s.push({period:i,payment,principal,interest,balance:bal})}return finalize(P,s)}
function flat(P,annual,n){const interest=P*(annual/100)*(n/12);return scheduleFixed(P,n,(P+interest)/n,interest)}
function simple(P,annual,n){const interest=P*(annual/100)*(n/12);return scheduleFixed(P,n,(P+interest)/n,interest)}
function interestOnly(P,annual,n){const monthlyInterest=P*(annual/1200),s=[];for(let i=1;i<=n;i++){const principal=i===n?P:0,payment=monthlyInterest+principal;s.push({period:i,payment,principal,interest:monthlyInterest,balance:i===n?0:P})}return finalize(P,s)}
function finalize(P,s){const total=s.reduce((a,x)=>a+x.payment,0),interest=s.reduce((a,x)=>a+x.interest,0);return{payment:s[0]?.payment||0,total,interest,schedule:s,principal:P}}
function calculate(v){if(v.method==='reducing')return reducing(v.P,v.rate,v.months);if(v.method==='flat')return flat(v.P,v.rate,v.months);if(v.method==='simple')return simple(v.P,v.rate,v.months);return interestOnly(v.P,v.rate,v.months)}
function annualize(rows){const out=[];for(let i=0;i<rows.length;i+=12){const g=rows.slice(i,i+12),last=g[g.length-1];out.push({period:'Year '+(Math.floor(i/12)+1),payment:g.reduce((a,x)=>a+x.payment,0),principal:g.reduce((a,x)=>a+x.principal,0),interest:g.reduce((a,x)=>a+x.interest,0),balance:last.balance})}return out}
function renderSchedule(view='monthly'){const rows=view==='yearly'?annualize(current.calc.schedule):current.calc.schedule;$('#schedule-body').replaceChildren(...rows.map(x=>{const tr=document.createElement('tr');[x.period,money.format(round(x.payment)),money.format(round(x.principal)),money.format(round(x.interest)),money.format(round(x.balance))].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});return tr}))}
function render(v,x){current={v,calc:x};$('#results').hidden=false;$('#payment-label').textContent=v.method==='interest-only'?'Initial monthly interest payment':'Estimated monthly payment';$('#payment').textContent=money.format(round(x.payment));$('#r-principal').textContent=money.format(v.P);$('#r-interest').textContent=money.format(round(x.interest));$('#r-total').textContent=money.format(round(x.total+v.fee));$('#r-fees').textContent=money.format(v.fee);const denom=v.P+x.interest,p=denom?v.P/denom*100:100;$('#principal-bar').style.width=p+'%';$('#interest-bar').style.width=(100-p)+'%';$('#split-text').textContent=`Principal ${p.toFixed(1)}% · Interest ${(100-p).toFixed(1)}%`;$('#method-note').textContent=`${v.type} · ${$('#interest-method').selectedOptions[0].textContent} · ${v.months} months`;renderSchedule();$('#results').scrollIntoView({behavior:'smooth',block:'start'})}
$('#loan-form').addEventListener('submit',e=>{e.preventDefault();const err=$('#form-error');try{err.hidden=true;const v=inputs();render(v,calculate(v))}catch(ex){err.textContent=ex.message;err.hidden=false}})
document.querySelectorAll('.view-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view-btn').forEach(x=>x.classList.toggle('active',x===b));renderSchedule(b.dataset.view)}));
function prepayImpact(){if(!current)return;const extra=Number($('#prepay').value);if(!Number.isFinite(extra)||extra<=0){$('#prepay-result').textContent='Enter an extra payment greater than zero.';return}const {v,calc}=current;if(v.method!=='reducing'){$('#prepay-result').textContent='Prepayment modelling is currently available for reducing-balance loans, where it can be calculated consistently.';return}if(extra>=v.P){$('#prepay-result').textContent='Extra payment must be less than the outstanding principal for this comparison.';return}const mode=$('#prepay-mode').value,newP=v.P-extra;let revised;if(mode==='emi')revised=reducing(newP,v.rate,v.months);else{const oldPay=calc.payment,r=v.rate/1200/100;let n;if(r===0)n=Math.ceil(newP/oldPay);else n=Math.ceil(-Math.log(1-r*newP/oldPay)/Math.log(1+r));if(!Number.isFinite(n)||n<1)n=1;revised=reducing(newP,v.rate,n)}const saved=Math.max(0,calc.interest-revised.interest);$('#prepay-result').innerHTML=`<div class="prepay-stats"><strong>Interest saved: ${money.format(round(saved))}</strong><span>New monthly payment: ${money.format(round(revised.payment))}</span><span>New tenure: ${revised.schedule.length} months</span><span>Months saved: ${Math.max(0,v.months-revised.schedule.length)}</span></div>`}
$('#prepay-btn').addEventListener('click',prepayImpact);
const helps={reducing:'Reducing balance calculates interest on the outstanding principal after each repayment.',flat:'Flat rate calculates interest on the original principal for the full tenure.',simple:'Simple interest uses principal × annual rate × time, then spreads principal and interest across the selected term.',"interest-only":'Interest-only keeps principal outstanding during the term; this model assumes the principal is repaid with the final payment.'};
function updateHelp(){$('#method-help').textContent=helps[$('#interest-method').value]}$('#interest-method').addEventListener('change',updateHelp);updateHelp();