import {createRequire} from 'module';const require=createRequire(import.meta.url),E=require('./loan-engine.js');const close=(a,b,t=.02)=>Math.abs(a-b)<=t,tests=[];function ok(v,m){if(!v)throw Error(m)}function test(n,f){try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}}
test('Reducing known answer',()=>{const x=E.reducing(500000,10,60);ok(close(x.payment,10623.52,.05),'EMI '+x.payment);ok(close(x.interest,137411.34,1),'interest');ok(x.schedule.length===60,'term');ok(close(x.schedule[59].balance,0),'balance')});
test('Zero interest',()=>{const x=E.reducing(100000,0,12);ok(close(x.total,100000),'total');ok(close(x.interest,0),'interest')});
test('Flat known answer',()=>{const x=E.flat(100000,12,12);ok(close(x.interest,12000),'interest');ok(close(x.total,112000),'total')});
test('Interest-only balloon',()=>{const x=E.interestOnly(100000,12,12);ok(close(x.payment,1000),'interest payment');ok(close(x.schedule[11].payment,101000),'balloon')});
test('Fixed-payment payoff preserves EMI exactly',()=>{const b=E.reducing(500000,10,60),x=E.fixedPaymentPayoff(400000,10,b.payment,60);ok(close(x.payment,b.payment,.000001),'EMI changed');ok(x.schedule.length<60,'term');ok(close(x.schedule[x.schedule.length-1].balance,0),'balance')});
test('Fixed-payment payoff rejects non-amortizing payment',()=>{let threw=false;try{E.fixedPaymentPayoff(100000,12,500,120)}catch(e){threw=true}ok(threw,'should reject')});
test('Step-up closes exactly',()=>{const x=E.stepped(500000,10,60,5,'up',12);ok(x.schedule[12].payment>x.schedule[0].payment,'not stepped up');ok(close(x.schedule[59].balance,0),'balance')});
test('Step-down closes exactly',()=>{const x=E.stepped(500000,10,60,5,'down',12);ok(x.schedule[12].payment<x.schedule[0].payment,'not stepped down');ok(close(x.schedule[59].balance,0),'balance')});
test('Balloon structure preserves final obligation',()=>{const x=E.balloon(500000,10,60,100000),last=x.schedule[59];ok(last.payment>x.schedule[0].payment,'final not ballooned');ok(close(last.payment,last.principal+last.interest,.02),'final cash payment mismatch');ok(close(last.balance,0),'balance')});
test('Prepayment reference case preserves EMI and saves tenure',()=>{const base=E.reducing(2000000,8.5,180),after=24,extra=300000,outstanding=base.schedule[after-1].balance,revised=E.fixedPaymentPayoff(outstanding-extra,8.5,base.payment,180-after);ok(close(revised.payment,base.payment,.000001),'EMI changed');ok(revised.schedule.length<180-after,'tenure not reduced');ok(close(revised.schedule[revised.schedule.length-1].balance,0),'balance')});
test('Capitalized moratorium increases repayment-start balance',()=>{const x=E.withMoratorium(500000,10,60,6,true);ok(x.balanceAtRepaymentStart>500000,'no capitalization');ok(x.schedule.length===66,'term');ok(close(x.schedule[65].balance,0),'balance')});
test('Interest-paid moratorium does not increase balance',()=>{const x=E.withMoratorium(500000,10,60,6,false);ok(close(x.balanceAtRepaymentStart,500000),'balance grew');ok(x.schedule.length===66,'moratorium should precede full repayment term');ok(x.schedule.slice(0,6).every(r=>r.payment>0),'interest not paid')});
test('Moratorium plus tenure cap is enforced',()=>{let threw=false;try{E.withMoratorium(500000,10,1190,11,true)}catch(e){threw=true}ok(threw,'combined term exceeded cap')});
test('Zero-percent step equals standard EMI',()=>{const a=E.reducing(500000,10,60),b=E.calculate({P:500000,rate:10,months:60,structure:'step-up',stepPct:0});ok(close(a.payment,b.payment,.0001),'zero step changed payment')});
test('Zero balloon equals standard reducing loan',()=>{const a=E.reducing(500000,10,60),b=E.calculate({P:500000,rate:10,months:60,structure:'balloon',balloon:0});ok(close(a.payment,b.payment,.0001),'zero balloon mismatch');ok(close(a.total,b.total,.05),'total mismatch')});
test('NaN step is rejected',()=>{let threw=false;try{E.calculate({P:500000,rate:10,months:60,structure:'step-up',stepPct:NaN})}catch(e){threw=true}ok(threw,'NaN silently accepted')});
test('NaN balloon is rejected',()=>{let threw=false;try{E.calculate({P:500000,rate:10,months:60,structure:'balloon',balloon:NaN})}catch(e){threw=true}ok(threw,'NaN silently accepted')});
test('Long tenure finite',()=>{const x=E.reducing(10000000,15,1200);ok(Number.isFinite(x.total),'nonfinite');ok(close(x.schedule[1199].balance,0),'balance')});
test('All schedules have canonical fields',()=>{for(const x of [E.reducing(1e6,8,120),E.stepped(1e6,8,120,4,'up',12),E.balloon(1e6,8,120,2e5)])for(const r of x.schedule)for(const k of ['period','opening','payment','principal','interest','extra','balance'])ok(Number.isFinite(r[k]),'bad '+k)});
test('Principal conservation',()=>{for(const x of [E.reducing(1234567,8.75,241),E.flat(765432,11.2,37),E.interestOnly(333333,9.9,19),E.balloon(900000,7.5,84,200000)])ok(close(x.schedule.reduce((a,r)=>a+r.principal+r.extra,0),x.principal,.08),'principal mismatch')});

test('Global monthly amortization reference cases',()=>{for(const [P,r,n] of [[400000,6.5,360],[250000,4.5,300],[600000,6,360],[500000,10,60],[12000,0,12]]){const x=E.reducing(P,r,n),m=r===0?P/n:(()=>{const q=r/1200,p=Math.pow(1+q,n);return P*q*p/(p-1)})();ok(close(x.payment,m,.000001),'reference payment');ok(close(x.schedule[n-1].balance,0,.02),'reference close')}});
test('Global principal-rate-term stress matrix',()=>{for(const P of [1,1000,100000,1e7,1e10])for(const r of [0,.01,1,5,10,25,100])for(const n of [1,6,12,60,360,600,1200]){const x=E.reducing(P,r,n);ok(Number.isFinite(x.payment)&&Number.isFinite(x.total),'nonfinite');ok(x.schedule.length===n,'schedule length');ok(close(x.schedule[n-1].balance,0,.08),'closing balance')}});
let failed=0;for(const [n,p,m] of tests){console.log(p?'PASS':'FAIL',n,m||'');if(!p)failed++}console.log((tests.length-failed)+'/'+tests.length+' tests passed');if(failed)process.exitCode=1;