global.window=global;require('./salary-engine.js');require('./salary-countries.js');const E=global.SalaryEngine,C=global.SalaryCountries;let pass=0;function ok(x,m){if(!x)throw Error(m);pass++}function close(a,b,t=.05){return Math.abs(a-b)<=t}
let x=E.run({inputType:'annualGross',amount:100000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,filing:'single',stateRate:0},C.US);ok(close(x.tax,13170),'US federal tax');ok(close(x.social,7650),'US FICA');ok(close(x.net,79180),'US net');\nx=E.run({inputType:'annualGross',amount:300000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,filing:'joint',stateRate:0},C.US);ok(close(x.social,18478.5),'US payroll Medicare withholding threshold');
x=E.run({inputType:'annualGross',amount:60000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,region:'England / Wales / Northern Ireland',pension:'yes'},C.GB);ok(close(x.tax,11432),'UK tax');ok(close(x.social,3210.6),'UK NI');
x=E.run({inputType:'annualGross',amount:1200000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,regime:'new',residency:'resident',ageBand:'under60',pfRate:12,pfWage:300000,professionalTax:0,oldDeductions:0},C.IN);ok(close(x.tax,0),'India 87A rebate');ok(close(x.social,36000),'India PF');\nx=E.run({inputType:'annualGross',amount:1200000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,regime:'new',residency:'nonresident',ageBand:'under60',pfRate:0,pfWage:0,professionalTax:0,oldDeductions:0},C.IN);ok(x.tax>0,'India non-resident no 87A rebate');\nx=E.run({inputType:'annualGross',amount:600000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,regime:'old',residency:'resident',ageBand:'80plus',pfRate:0,pfWage:0,professionalTax:0,oldDeductions:0},C.IN);ok(close(x.tax,10400),'India old-regime super senior');
x=E.run({inputType:'annualGross',amount:100000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,medicare:'yes'},C.AU);ok(close(x.tax,20520),'AU 2026-27 income tax');ok(close(x.social,2000),'AU Medicare');
x=E.run({inputType:'annualGross',amount:120000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,manualSocial:0},C.AE);ok(x.tax===0&&x.net===120000,'UAE zero PIT');
x=E.run({inputType:'annualGross',amount:100000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,resident:'resident',cpf:0,reliefs:0},C.SG);ok(close(x.tax,5650),'Singapore resident tax');
x=E.run({inputType:'totalComp',amount:110000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:10000,manualTaxRate:0,manualSocialRate:0},C.OTHER);ok(close(x.gross,100000),'total compensation conversion');ok(close(x.employerCost,110000),'employer cost');\nx=E.run({inputType:'net',amount:5000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,manualTaxRate:20,manualSocialRate:5},C.OTHER);ok(close(x.monthlyNet,5000,.02),'reverse solver');ok(x.gross>0,'reverse gross');
console.log('Salary engine tests passed:',pass);
// Boundary and invariant audit
for(const [code,base] of Object.entries({US:{filing:'single',stateRate:0},GB:{region:'England / Northern Ireland',pension:'yes'},AU:{medicare:'yes'},AE:{manualSocial:0},SG:{resident:'resident',cpf:0,reliefs:0},OTHER:{manualTaxRate:20,manualSocialRate:5}})){const cc=C[code];for(const amount of [0,1,1000,25000,50000,100000]){const v=Object.assign({inputType:'annualGross',amount,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0},base),z=E.run(v,cc);ok(Number.isFinite(z.net)&&z.net>=0&&z.net<=z.gross+1e-7,code+' net invariant '+amount);ok(z.tax>=0&&z.social>=0,code+' charge invariant '+amount)}}
for(const target of [1000,3000,5000,10000]){const v={inputType:'net',amount:target,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,manualTaxRate:20,manualSocialRate:5},z=E.run(v,C.OTHER);ok(close(z.monthlyNet,target,.02),'reverse round trip '+target)}
let threw=false;try{E.run({inputType:'annualGross',amount:1000,hours:40,bonus:0,pretax:0,otherDeductions:2000,employerBenefits:0,manualTaxRate:0,manualSocialRate:0},C.OTHER)}catch{threw=true}ok(threw,'reject excessive deductions');
console.log('Deep audit tests passed:',pass);
// India surcharge / marginal-relief boundaries
function indiaTax(income,regime='new'){return E.run({inputType:'annualGross',amount:income+(regime==='new'?75000:50000),hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,regime,residency:'resident',ageBand:'under60',pfRate:0,pfWage:0,professionalTax:0,oldDeductions:0},C.IN).tax}
for(const t of [5000000,10000000,20000000]){const at=indiaTax(t),above=indiaTax(t+1);ok(above>=at&&above-at<=1.05,'India new marginal boundary '+t)}
for(const t of [5000000,10000000,20000000,50000000]){const at=indiaTax(t,'old'),above=indiaTax(t+1,'old');ok(above>=at&&above-at<=1.05,'India old marginal boundary '+t)}
ok(indiaTax(60000000,'old')>indiaTax(60000000,'new'),'India old 37% surcharge above 5cr');
// India 87A marginal relief immediately above ₹12 lakh taxable income
const i12=indiaTax(1200000),i120001=indiaTax(1200001),i125=indiaTax(1250000);ok(close(i12,0),'India 87A at 12L');ok(i120001>0&&i120001<=1.05,'India 87A marginal relief +1');ok(i125<=52000.05,'India 87A marginal relief 12.5L');
// Release-blocker regression cases
x=E.run({inputType:'annualGross',amount:36000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,regime:'new',residency:'resident',ageBand:'under60',pfRate:0,pfWage:0,region:'Telangana',professionalTax:0,oldDeductions:0},C.IN);ok(close(x.social,2400),'Telangana PT');
x=E.run({inputType:'annualGross',amount:40000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,pension:'yes',studentLoan:'p5',postgradLoan:'yes',region:'England / Northern Ireland'},C.GB);ok(close(x.social,2194.4+1350+1140),'UK NI + Plan5 + postgraduate');
x=E.run({inputType:'annualGross',amount:96000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,resident:'resident',cpfStatus:'citizen',cpfAge:'55under',cpf:0,reliefs:0},C.SG);ok(close(x.social,19200),'Singapore employee CPF');ok(close(x.employerCost,112320),'Singapore employer CPF in cost');
x=E.run({inputType:'annualGross',amount:100000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,region:'Ontario'},C.CA);ok(x.tax>0&&x.social>0,'Canada Ontario modeled payroll');
x=E.run({inputType:'annualGross',amount:100000,hours:40,bonus:0,pretax:0,otherDeductions:0,employerBenefits:0,medicare:'no',help:'yes'},C.AU);ok(close(x.tax,20252),'AU 2026-27 14% band');ok(close(x.social,4570.8),'AU HELP marginal repayment');
x=E.run({inputType:'totalComp',amount:120000,hours:40,bonus:10000,pretax:0,otherDeductions:0,employerBenefits:5000,resident:'resident',cpfStatus:'citizen',cpfAge:'55under',cpf:0,reliefs:0},C.SG);ok(close(x.employerCost,120000,.05),'Total compensation constrains employer cost with statutory employer CPF');