import {$,el,notice,setupStatus,status} from '../../assets/js/core.js';
const root=$('#workspace');if(!root)throw Error('BMI calculator workspace unavailable.');
const KG_PER_LB=0.45359237,CM_PER_IN=2.54;
const css=el('style',{text:`.bmi{max-width:720px;margin:auto}.bmi-switch{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:16px}.bmi-switch button{min-height:46px}.bmi-switch button[aria-pressed="true"]{font-weight:800;outline:2px solid currentColor}.bmi-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.bmi-field{display:grid;gap:6px}.bmi-field label{font-weight:700}.bmi-field input{width:100%;min-height:46px}.bmi-height-imperial{display:grid;grid-template-columns:1fr 1fr;gap:8px}.bmi-actions{display:flex;gap:8px;margin:16px 0}.bmi-actions button{flex:1;min-height:46px}.bmi-result{border:1px solid var(--line);border-radius:16px;padding:16px;margin-top:12px}.bmi-result[hidden]{display:none}.bmi-score{font-size:34px;font-weight:800}.bmi-category{font-size:20px;font-weight:700;margin:3px 0 14px}.bmi-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.bmi-card{background:var(--surface-2,#f5f7f6);border-radius:12px;padding:12px}.bmi-card small{display:block;color:var(--muted);margin-bottom:4px}.bmi-card strong{font-size:18px}.bmi-table{width:100%;margin-top:14px;border-collapse:collapse}.bmi-table th,.bmi-table td{text-align:left;padding:8px;border-bottom:1px solid var(--line)}.bmi-help{font-size:14px;color:var(--muted);margin-top:14px}.bmi-source{margin-top:10px}@media(max-width:600px){.bmi-fields{grid-template-columns:1fr}.bmi-field input,.bmi-switch button,.bmi-actions button{font-size:16px}.bmi-grid{grid-template-columns:1fr}}`});root.prepend(css);
let units='metric';
const metricBtn=el('button',{type:'button',class:'button',text:'Metric (kg / cm)','aria-pressed':'true'});
const imperialBtn=el('button',{type:'button',class:'button',text:'Imperial (lb / ft + in)','aria-pressed':'false'});
const metricHeight=field('heightCm','Height','cm','170',{min:91.44,max:274.32,step:'any'});
const metricWeight=field('weightKg','Weight','kg','65',{min:24.947,max:453.592,step:'any'});
const feet=numberInput('heightFt','Feet','ft','5',3,9,1),inches=numberInput('heightIn','Inches','in','7',0,11.999999,'any');
const imperialHeight=el('div',{class:'bmi-field'},[el('label',{text:'Height'}),el('div',{class:'bmi-height-imperial'},[feet, inches])]);
const imperialWeight=field('weightLb','Weight','lb','143',{min:55,max:1000,step:'any'});
const fields=el('div',{class:'bmi-fields'});
const result=el('section',{class:'bmi-result',hidden:true,'aria-live':'polite'});
const calc=el('button',{type:'button',class:'button primary',text:'Calculate BMI'}),reset=el('button',{type:'button',class:'button',text:'Reset'});
root.append(el('div',{class:'bmi'},[el('div',{class:'bmi-switch'},[metricBtn,imperialBtn]),fields,el('div',{class:'bmi-actions'},[calc,reset]),result]));
function numberInput(id,labelText,suffix,value,min,max,step){const input=el('input',{id,type:'number',value,min,max,step,inputmode:'decimal','aria-label':labelText+' ('+suffix+')'});return el('div',{class:'bmi-field'},[el('label',{for:id,text:labelText+' ('+suffix+')'}),input])}
function field(id,labelText,suffix,value,opts){const input=el('input',{id,type:'number',value,inputmode:'decimal',...opts});return el('div',{class:'bmi-field'},[el('label',{for:id,text:labelText+' ('+suffix+')'}),input])}
function sync(){metricBtn.setAttribute('aria-pressed',String(units==='metric'));imperialBtn.setAttribute('aria-pressed',String(units==='imperial'));fields.replaceChildren(...(units==='metric'?[metricHeight,metricWeight]:[imperialHeight,imperialWeight]));result.hidden=true}
function val(id,min,max){const node=$('#'+id),raw=node?node.value.trim():'';if(raw==='')throw Error('Complete all required fields.');const v=Number(raw);if(!Number.isFinite(v)||v<min||v>max)throw Error('Check the entered height and weight.');return v}
function category(b){if(b<18.5)return 'Underweight';if(b<25)return 'Healthy weight';if(b<30)return 'Overweight';if(b<35)return 'Obesity — Class I';if(b<40)return 'Obesity — Class II';return 'Obesity — Class III'}
function fmt(n,d=1){return n.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d})}
function calculate(){try{let cm,kg;if(units==='metric'){cm=val('heightCm',91.44,274.32);kg=val('weightKg',24.94758035,453.59237)}else{const ft=val('heightFt',3,9),inch=val('heightIn',0,11.999999);if(!Number.isInteger(ft))throw Error('Enter feet as a whole number.');const totalIn=ft*12+inch;if(totalIn<36||totalIn>108)throw Error('Enter a total height from 3 ft to 9 ft.');cm=totalIn*CM_PER_IN;kg=val('weightLb',55,1000)*KG_PER_LB}const m=cm/100,bmi=kg/(m*m),lowKg=18.5*m*m,highKg=24.9*m*m;const range=units==='metric'?fmt(lowKg)+'–'+fmt(highKg)+' kg':fmt(lowKg/KG_PER_LB)+'–'+fmt(highKg/KG_PER_LB)+' lb';result.hidden=false;result.replaceChildren(el('div',{class:'bmi-score',text:fmt(bmi)}),el('div',{class:'bmi-category',text:category(bmi)}),el('div',{class:'bmi-grid'},[el('div',{class:'bmi-card'},[el('small',{text:'Healthy-weight reference range for this height'}),el('strong',{text:range})]),el('div',{class:'bmi-card'},[el('small',{text:'Adult healthy BMI reference'}),el('strong',{text:'18.5–24.9 kg/m²'})])]),table(),el('p',{class:'bmi-help',text:'BMI is a screening measure based only on height and weight. It does not diagnose a health condition or directly measure body fat. Interpretation may require other health information.'}),el('p',{class:'bmi-help',text:'For adults only. Do not use this adult classification for children or teens. BMI also needs clinical context in pregnancy and in people whose muscle mass or body composition makes BMI less representative.'}),el('p',{class:'bmi-source'},[el('span',{text:'Adult BMI classification reference: '}),el('a',{href:'https://www.who.int/europe/news-room/fact-sheets/item/nutrition---maintaining-a-healthy-lifestyle',target:'_blank',rel:'noopener',text:'World Health Organization ↗'})]));status('BMI calculated.')}catch(e){result.hidden=true;status(e.message||'Unable to calculate BMI.',true)}}
function table(){const rows=[['Underweight','Below 18.5'],['Healthy weight','18.5–24.9'],['Overweight','25.0–29.9'],['Obesity — Class I','30.0–34.9'],['Obesity — Class II','35.0–39.9'],['Obesity — Class III','40.0 or above']];return el('table',{class:'bmi-table'},[el('thead',{},el('tr',{},[el('th',{text:'Adult classification'}),el('th',{text:'BMI'})])),el('tbody',{},rows.map(r=>el('tr',{},r.map(x=>el('td',{text:x})))) )])}
function switchUnits(next){if(next===units)return;try{if(units==='metric'){const cm=val('heightCm',91.44,274.32),kg=val('weightKg',24.94758035,453.59237),totalIn=cm/CM_PER_IN,ft=Math.floor(totalIn/12),inch=totalIn-ft*12;feet.querySelector('input').value=String(ft);inches.querySelector('input').value=String(Number(inch.toFixed(4)));imperialWeight.querySelector('input').value=String(Number((kg/KG_PER_LB).toFixed(4)))}else{const ft=val('heightFt',3,9),inch=val('heightIn',0,11.999999),lb=val('weightLb',55,1000);if(!Number.isInteger(ft))throw Error('Enter feet as a whole number.');const totalIn=ft*12+inch;if(totalIn<36||totalIn>108)throw Error('Enter a total height from 3 ft to 9 ft.');metricHeight.querySelector('input').value=String(Number((totalIn*CM_PER_IN).toFixed(4)));metricWeight.querySelector('input').value=String(Number((lb*KG_PER_LB).toFixed(4)))}units=next;sync();status('Units converted.')}catch(e){status(e.message||'Check the current values before switching units.',true)}}
metricBtn.onclick=()=>switchUnits('metric');imperialBtn.onclick=()=>switchUnits('imperial');calc.onclick=calculate;reset.onclick=()=>{metricHeight.querySelector('input').value='170';metricWeight.querySelector('input').value='65';feet.querySelector('input').value='5';inches.querySelector('input').value='7';imperialWeight.querySelector('input').value='143';units='metric';sync();status('Inputs reset.')};sync();setupStatus(root);notice(root,'Adult BMI screening calculator. Results are reference information, not a diagnosis or personalized medical advice.');