import {$,el,setupStatus,status,notice} from '../../assets/js/core.js';
const root=$('#workspace');if(!root)throw Error('Percentage Calculator workspace unavailable.');
const MODES={
 percent:{label:'Percent of a number',a:'Percentage (%)',b:'Number',av:'10',bv:'100',hint:'Find X% of Y.'},
 ratio:{label:'What percentage?',a:'Part',b:'Whole',av:'25',bv:'100',hint:'Find what percentage the part is of the whole.'},
 change:{label:'Percentage change',a:'Original value',b:'New value',av:'100',bv:'125',hint:'Measure increase or decrease from the original value.'},
 discount:{label:'Discount',a:'Original price / amount',b:'Discount (%)',av:'100',bv:'20',hint:'Find the discount amount and amount after discount.'},
 tip:{label:'Tip',a:'Bill / base amount',b:'Tip (%)',av:'100',bv:'15',hint:'Find the tip amount and total.'}
};
const css=el('style',{text:`.pct{max-width:720px;margin:auto}.pct-modes{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pct-modes button{min-height:46px;text-align:left}.pct-modes button[aria-pressed="true"]{font-weight:800;outline:2px solid currentColor}.pct-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.pct-field{display:grid;gap:6px}.pct-field label{font-weight:700}.pct-field input{width:100%;min-height:46px}.pct-hint{color:var(--muted);margin:10px 0 0}.pct-actions{display:flex;gap:8px;margin:16px 0}.pct-actions button{flex:1;min-height:46px}.pct-result{border:1px solid var(--line);border-radius:16px;padding:16px;margin-top:12px}.pct-result[hidden]{display:none}.pct-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.pct-card{background:var(--surface-2,#f5f7f6);border-radius:12px;padding:12px}.pct-card small{display:block;color:var(--muted);margin-bottom:4px}.pct-card strong{font-size:22px}.pct-note{font-size:14px;color:var(--muted);margin-top:12px}@media(max-width:600px){.pct-modes,.pct-fields,.pct-grid{grid-template-columns:1fr}.pct-field input,.pct-modes button,.pct-actions button{font-size:16px}}`});root.prepend(css);
let mode='percent';
const modeWrap=el('div',{class:'pct-modes'}),fields=el('div',{class:'pct-fields'}),hint=el('p',{class:'pct-hint'}),result=el('section',{class:'pct-result',hidden:true,'aria-live':'polite'});
const inputA=field('pctA'),inputB=field('pctB');
for(const [key,m] of Object.entries(MODES)){const b=el('button',{type:'button',class:'button',text:m.label,'aria-pressed':String(key===mode)});b.onclick=()=>setMode(key);b.dataset.mode=key;modeWrap.append(b)}
const calc=el('button',{type:'button',class:'button primary',text:'Calculate'}),reset=el('button',{type:'button',class:'button',text:'Reset'});
root.append(el('div',{class:'pct'},[modeWrap,hint,fields,el('div',{class:'pct-actions'},[calc,reset]),result]));
function field(id){const input=el('input',{id,type:'number',step:'any',inputmode:'decimal'}),label=el('label',{for:id});return el('div',{class:'pct-field'},[label,input])}
function node(w){return w.querySelector('input')}function label(w){return w.querySelector('label')}
function setMode(next){mode=next;const m=MODES[mode];for(const b of modeWrap.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));label(inputA).textContent=m.a;label(inputB).textContent=m.b;node(inputA).value=m.av;node(inputB).value=m.bv;fields.replaceChildren(inputA,inputB);hint.textContent=m.hint;result.hidden=true;status('Mode changed to '+m.label+'.')}
function value(w,name){const raw=node(w).value.trim();if(raw==='')throw Error('Enter '+name+'.');const v=Number(raw);if(!Number.isFinite(v)||Math.abs(v)>1e15)throw Error(name+' must be a finite number within the supported range.');return v}
function fmt(v){if(!Number.isFinite(v))throw Error('The result is outside the supported range.');const a=Math.abs(v);if(a!==0&&(a>=1e12||a<1e-9))return v.toExponential(10).replace(/\.0+e/,'e');return v.toLocaleString(undefined,{maximumSignificantDigits:12,useGrouping:true})}
function card(name,v){return el('div',{class:'pct-card'},[el('small',{text:name}),el('strong',{text:v})])}
function calculate(){try{const a=value(inputA,MODES[mode].a),b=value(inputB,MODES[mode].b);let cards=[],note='';if(mode==='percent'){cards=[card('Result',fmt(a*b/100))];note=fmt(a)+'% of '+fmt(b)+'.'}else if(mode==='ratio'){if(b===0)throw Error('Whole cannot be zero.');cards=[card('Percentage',fmt(a/b*100)+'%')];note='Part ÷ whole × 100.'}else if(mode==='change'){if(a===0)throw Error('Percentage change is undefined when the original value is zero.');const pct=(b-a)/Math.abs(a)*100;cards=[card('Percentage change',fmt(pct)+'%'),card('Absolute change',fmt(b-a))];note=pct>0?'Increase from the original value.':pct<0?'Decrease from the original value.':'No change.'}else if(mode==='discount'){if(a<0)throw Error('Original amount cannot be negative.');if(b<0||b>100)throw Error('Discount must be between 0% and 100%.');const d=a*b/100;cards=[card('Discount amount',fmt(d)),card('After discount',fmt(a-d))];note='Discount is applied once to the original amount.'}else if(mode==='tip'){if(a<0)throw Error('Bill / base amount cannot be negative.');if(b<0)throw Error('Tip percentage cannot be negative.');const t=a*b/100;cards=[card('Tip amount',fmt(t)),card('Total',fmt(a+t))];note='Tip is calculated from the entered base amount.'}result.hidden=false;result.replaceChildren(el('div',{class:'pct-grid'},cards),el('p',{class:'pct-note',text:note}));status('Calculation complete.')}catch(e){result.hidden=true;status(e.message||'Unable to calculate.',true)}}
calc.onclick=calculate;reset.onclick=()=>{setMode('percent');status('Inputs reset.')};setMode('percent');setupStatus(root);notice(root,'Calculations use the values you enter. Percentage change uses the absolute original value as its denominator so the sign indicates increase or decrease.');