import fs from 'node:fs/promises';
import path from 'node:path';
import {tools,categories,popular,findTool} from '../dist/assets/js/catalog.js';
const config=JSON.parse(await fs.readFile('site-config.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={briefcase:'M3 7h18v14H3z M8 7V3h8v4 M3 12h18 M10 12v3h4v-3',file:'M6 2h8l5 5v15H6z M14 2v6h5 M9 12h7 M9 16h7',image:'M3 3h18v18H3z M3 17l6-6 5 5 3-3 4 4 M15 7h.01',calculator:'M5 2h14v20H5z M8 5h8v4H8z M8 13h1 M15 13h1 M8 17h1 M15 17h1',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',shield:'M12 2l8 4v6c0 5-8 10-8 10S4 17 4 12V6z M8 12l3 3 5-6',arrow:'M6 12h12 M13 7l5 5-5 5',pen:'M4 20l1-5L17 3l4 4L9 19z M14 6l4 4',merge:'M5 3v5l7 7v6 M19 3v5l-7 7 M8 17l4 4 4-4',clock:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M12 6v6l4 2'};
const icon=n=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[n]||paths.file}"/></svg>`;
const favicon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#145940"/><text x="32" y="43" font-family="Arial,sans-serif" font-size="31" font-weight="bold" text-anchor="middle" fill="white">AF</text></svg>';
await fs.writeFile('dist/favicon.svg',favicon);
const routes=['',...categories.map(c=>c[0]+'/'),...tools.map(t=>t.path),'request/','about/','privacy/'];
function page(route,title,description,body,attrs=''){const prefix=route?'../'.repeat(route.split('/').filter(Boolean).length):'./';const a=p=>prefix+p;const cat=route.split('/')[0];const canonical=config.domain?`<link rel="canonical" href="${esc(new URL(route,config.domain.endsWith('/')?config.domain:config.domain+'/').href)}">`:'';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)} | AllToolForest</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#145940"><meta property="og:title" content="${esc(title)} | AllToolForest"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">${canonical}<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,${encodeURIComponent(favicon)}"><link rel="manifest" href="${a('site.webmanifest')}"><link rel="stylesheet" href="${a('assets/css/main.css')}"><script type="module" src="${a('assets/js/app.js')}"></script></head><body ${attrs}><a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="${a('')}"><span class="brand-mark">AF</span>AllToolForest</a><nav class="nav" aria-label="Main navigation">${categories.map(c=>`<a class="${cat===c[0]?'active':''}" href="${a(c[0]+'/')}">${c[1]}</a>`).join('')}</nav><span class="header-note">${icon('shield')}No account needed</span></div></header><main class="container" id="main">${body.replaceAll('@@',prefix)}</main><footer class="site-footer"><span>© ${new Date().getUTCFullYear()} AllToolForest · Made for everyday work.</span><div class="footer-links"><a href="${a('about/')}">About</a><a href="${a('privacy/')}">Privacy</a><a href="${a('request/')}">Request a tool</a></div></footer></body></html>`}
const card=(t,prefix='@@')=>`<a class="tool-card" href="${prefix+t.path}">${icon(t.icon)}<div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p></div></a>`;
async function write(route,title,desc,body,attrs){const file=route?'dist/'+route+'index.html':'dist/index.html';await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,page(route,title,desc,body,attrs))}
await write('','Simple, private tools for everyday work','Free browser tools for documents, images, work and everyday calculations.',`<section class="hero"><div class="eyebrow">A little less busywork</div><h1>Simple, private tools<br>for <span>everyday work.</span></h1><p>Your files, figures and finishing touches. All in one place.</p><div class="search-wrap"><label class="search-box" for="search">${icon('search')}<input id="search" type="search" placeholder="What would you like to do?" aria-label="Search tools" autocomplete="off"><span class="search-key">/</span></label><div id="search-results" class="search-results" hidden></div></div><p class="search-caption">Try “edit PDF”, “resize image” or “loan calculator”</p></section><section><div class="section-heading"><h2>Find your workspace</h2><span style="font-size:13px;color:var(--muted)">Four categories. Less clutter.</span></div><div class="category-grid">${categories.map(([slug,title,desc,i])=>`<a class="category-card" href="@@${slug}/"><span class="icon-box">${icon(i)}</span><span class="card-arrow">${icon('arrow')}</span><h3>${title}</h3><p>${desc}</p><span class="count">${tools.filter(t=>t.category===slug).length} tools</span></a>`).join('')}</div></section><section><div class="section-heading"><h2>A few everyday favorites</h2><a href="#all-tools">Explore all tools ↗</a></div><div class="tool-grid">${popular.map(s=>card(findTool(s))).join('')}</div></section><div class="trust-strip"><span>${icon('shield')}Browser-side processing</span><span>${icon('file')}No account needed</span><span>${icon('clock')}Ready when you are</span></div><details id="all-tools" style="margin-top:25px"><summary class="button">Explore all ${tools.length} tools</summary>${categories.map(c=>`<div class="section-heading"><h2>${c[1]}</h2></div><div class="tool-grid">${tools.filter(t=>t.category===c[0]).map(t=>card(t)).join('')}</div>`).join('')}</details>`);
for(const c of categories){let extra=c[0]==='images'?`<div class="section-heading"><h2>Related workflows</h2></div><div class="tool-grid">${['application-document-prep','image-to-text'].map(s=>card(findTool(s))).join('')}</div>`:'';await write(c[0]+'/',c[1]+' tools',c[2],`<div class="breadcrumb"><a href="@@">Home</a><span>/</span>${c[1]}</div><section class="page-intro"><h1>${c[1]}</h1><p>${c[2].replace(/\.$/,'')}.</p></section><div class="tool-grid">${tools.filter(t=>t.category===c[0]).map(t=>card(t)).join('')}</div>${extra}<p style="margin-top:30px"><a href="@@request/">Missing something? Request a tool ↗</a></p>`)}
for(const t of tools){const related=tools.filter(x=>x.category===t.category&&x.slug!==t.slug).slice(0,3);await write(t.path,t.title,t.description,`<div class="breadcrumb"><a href="@@">Home</a><span>/</span><a href="@@${t.category}/">${categories.find(c=>c[0]===t.category)[1]}</a><span>/</span>${esc(t.title)}</div><section class="page-intro"><h1>${esc(t.title)}</h1><p>${esc(t.description)}</p></section><div class="tool-layout"><section class="workspace" id="workspace" aria-label="${esc(t.title)} workspace"></section><aside class="side-note"><h2>Your work stays yours.</h2><p>File processing happens in your browser. Some tools load models from third-party services.</p><a href="@@privacy/">How your data is handled ↗</a><hr style="border:0;border-top:1px solid var(--line);margin:26px 0"><h2>Also useful</h2>${related.map(r=>`<a href="@@${r.path}">${esc(r.title)}</a>`).join('')}<a href="@@request/">Suggest an improvement ↗</a></aside></div>`,`data-tool="${t.slug}"`)}
await write('request/','Request a tool','Suggest a tool or improvement without giving personal information.',`<div class="breadcrumb"><a href="@@">Home</a><span>/</span>Request a tool</div><section class="page-intro"><h1>Request a tool or suggest an improvement</h1><p>Tell us about the task. No name, email or phone number needed.</p></section><section class="workspace prose" id="workspace"></section>`,'data-page="request"');
await write('about/','About','Focused tools for everyday tasks, on phone and desktop.',`<div class="breadcrumb"><a href="@@">Home</a><span>/</span>About</div><article class="prose"><section class="page-intro"><h1>A little less busywork.</h1><p>AllToolForest brings useful everyday workflows into four focused spaces: Work, Documents, Images and Calculators.</p></section><h2>Simple by design</h2><p>Open a tool, bring your file or information, and leave with a useful result. No account is required. The tools work on your device, with practical limits explained where they matter.</p><h2>Honest about what a tool can do</h2><p>PDF overlays change appearance; they do not securely redact text. Resume matching compares words; it does not predict hiring decisions. Image enlargement uses resampling; it does not reconstruct missing detail. Calculators show estimates under stated assumptions.</p><h2>Built around your tasks</h2><p>We review suggestions for usefulness, demand, privacy, feasibility and fit with existing workflows.</p><p><a class="button" href="@@request/">Request a tool</a></p><h2>Open source</h2><p>The application is distributed under AGPL-3.0, with dependency notices included. <a href="@@alltoolforest-source.zip">Download the corresponding source</a>.</p>${config.publicContactEmail?`<h2>Contact</h2><a href="mailto:${esc(config.publicContactEmail)}">${esc(config.publicContactEmail)}</a>`:''}</article>`);
await write('privacy/','Privacy','How AllToolForest handles files, dependencies and calculations.',`<div class="breadcrumb"><a href="@@">Home</a><span>/</span>Privacy</div><article class="prose"><section class="page-intro"><h1>Your files. Your workspace.</h1><p>Privacy information · Updated ${new Date().toISOString().slice(0,10)}</p></section><h2>File processing</h2><p>File processing happens in your browser. The application does not upload selected files to a server. Files remain in page memory while you work; refreshing or leaving the page clears the working session. Export anything you want to keep.</p><h2>Libraries and model downloads</h2><p>Most processing libraries are served with this website and loaded only when needed. OCR downloads English language data from jsDelivr. Background removal downloads its model and runtime assets from IMG.LY. These providers receive network information such as your IP address and browser headers. File content is not included in those requests. Your browser may cache downloaded assets.</p><h2>Website hosting</h2><p>The website host receives normal HTTP requests and may retain access and security logs. This mobile review version is hosted on GitHub Pages. Production hosting and a public contact method must be identified before a public commercial launch.</p><h2>Accounts, analytics and advertising</h2><p>AllToolForest tools require no account. No advertising or analytics scripts are included. A private review deployment may separately require host authentication. Adding analytics, advertising, server processing or cookies will require an updated policy and any applicable consent controls before activation.</p><h2>Requests and external links</h2><p>Tool requests are prepared locally. Choosing a GitHub submission opens GitHub; its account requirements, terms and privacy policy apply. Do not include personal or confidential information in public requests.</p><h2>Calculations and document limitations</h2><p>Financial and health calculations are informational estimates, not professional advice. The privacy inspector is a limited pattern check, not a forensic review. Visual PDF replacement covers visible content; the original text may still be recoverable.</p><h2>Contact</h2><p>${config.publicContactEmail?`Privacy questions: <a href="mailto:${esc(config.publicContactEmail)}">${esc(config.publicContactEmail)}</a>.`:'A public contact address has not yet been configured for this review version.'}</p></article>`);
const basePath=(config.basePath||'/').replace(/\/?$/,'/');
await fs.writeFile('dist/404.html',page('','Page not found','This page could not be found.',`<section class="hero"><div class="eyebrow">404 · A wrong turn</div><h1>Let’s get you back.</h1><p>The page you’re looking for isn’t here.</p><a class="button primary" href="${esc(basePath)}">Go home</a></section>`));
await fs.writeFile('dist/site-config.json',JSON.stringify(config,null,2));
await fs.writeFile('dist/site.webmanifest',JSON.stringify({name:'AllToolForest',short_name:'AF',start_url:'./',display:'standalone',background_color:'#f8faf9',theme_color:'#145940',icons:[{src:'favicon.svg',sizes:'any',type:'image/svg+xml',purpose:'any'}]}));
const domain=config.domain||'https://FINAL-DOMAIN';
await fs.writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${esc(domain.replace(/\/$/,'')+'/'+r)}</loc></url>`).join('')}</urlset>`);
await fs.writeFile('dist/robots.txt',config.domain?`User-agent: *\nAllow: /\nSitemap: ${domain.replace(/\/$/,'')}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n# Private review build. Set domain in site-config.json and rebuild before public launch.\n');
console.log(`Generated ${routes.length+1} HTML pages · release ${config.release||'development'}. Domain ${config.domain||'pending — indexing disabled'}.`);
