import fs from 'node:fs/promises';
import path from 'node:path';
import {build} from 'esbuild';
const dir='dist/assets/vendor';await fs.mkdir(dir,{recursive:true});
const copies=[['pdf-lib/dist/pdf-lib.min.js','pdf-lib.js'],['pdfjs-dist/build/pdf.min.mjs','pdf.mjs'],['pdfjs-dist/build/pdf.worker.min.mjs','pdf.worker.mjs'],['mammoth/mammoth.browser.min.js','mammoth.js'],['dompurify/dist/purify.min.js','purify.js'],['docx/dist/index.iife.js','docx.js'],['exceljs/dist/exceljs.min.js','excel.js'],['papaparse/papaparse.min.js','csv.js'],['heic2any/dist/heic2any.min.js','heic.js'],['tesseract.js/dist/tesseract.min.js','ocr.js'],['tesseract.js/dist/worker.min.js','tesseract-worker.js']];
for(const [src,dest]of copies)await fs.copyFile('node_modules/'+src,dir+'/'+dest);
for(const folder of ['cmaps','standard_fonts','wasm'])await fs.cp('node_modules/pdfjs-dist/'+folder,dir+'/'+folder,{recursive:true});
await fs.mkdir(dir+'/tesseract-core',{recursive:true});for(const filename of await fs.readdir('node_modules/tesseract.js-core'))if(/\.(wasm|js)$/.test(filename))await fs.copyFile('node_modules/tesseract.js-core/'+filename,dir+'/tesseract-core/'+filename);
await build({entryPoints:['node_modules/@imgly/background-removal/dist/index.mjs'],outfile:dir+'/background.mjs',bundle:true,format:'esm',platform:'browser',minify:true,target:'es2022'});
const manifest={pdf:{script:'assets/vendor/pdf-lib.js',global:'PDFLib'},pdfjs:{module:'assets/vendor/pdf.mjs'},mammoth:{script:'assets/vendor/mammoth.js',global:'mammoth'},purify:{script:'assets/vendor/purify.js',global:'DOMPurify'},docx:{script:'assets/vendor/docx.js',global:'docx'},excel:{script:'assets/vendor/excel.js',global:'ExcelJS'},csv:{script:'assets/vendor/csv.js',global:'Papa'},heic:{script:'assets/vendor/heic.js',global:'heic2any'},ocr:{script:'assets/vendor/ocr.js',global:'Tesseract'},background:{module:'assets/vendor/background.mjs'}};await fs.writeFile(dir+'/manifest.json',JSON.stringify(manifest,null,2));
const p=JSON.parse(await fs.readFile('package.json','utf8')),notices=[];await fs.mkdir(dir+'/licenses',{recursive:true});for(const name of Object.keys(p.dependencies)){const base='node_modules/'+name;const pkg=JSON.parse(await fs.readFile(base+'/package.json','utf8'));notices.push(`${name} ${pkg.version} — ${typeof pkg.license==='string'?pkg.license:JSON.stringify(pkg.license)}`);for(const f of await fs.readdir(base)){if(/^licen[cs]e|^notice|^copying/i.test(f)){const target=dir+'/licenses/'+name.replaceAll('/','-')+'-'+f;try{await fs.copyFile(base+'/'+f,target)}catch{}}}}
await fs.writeFile(dir+'/THIRD-PARTY-NOTICES.txt',notices.join('\n')+'\n\nSee package-lock.json for exact transitive versions. IMG.LY model assets are downloaded on demand from its configured public path.\n');await fs.copyFile('node_modules/@imgly/background-removal/LICENSE.md','LICENSE');console.log('Vendored processing engines; models remain on demand.');
